apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "knp.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "knp.labels" . | nindent 4 }}
    {{- with .Values.daemonset.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.daemonset.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "knp.selectorLabels" . | nindent 6 }}
  {{- with .Values.daemonset.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "knp.labels" . | nindent 8 }}
        {{- with .Values.daemonset.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.daemonset.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccountName: {{ include "knp.serviceAccountName" . }}
      {{- with .Values.daemonset.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonset.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.daemonset.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: kube-network-policies
          image: {{ include "knp.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [/bin/netpol]
          args:
            - --hostname-override=$(MY_NODE_NAME)
            - --v={{ .Values.logLevel }}
            - --nfqueue-id={{ .Values.nfqueueId }}
            {{- range .Values.extraArgs }}
            - {{ . | quote }}
            {{- end }}
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- with .Values.daemonset.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          {{- with .Values.daemonset.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.daemonset.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
      volumes:
        - name: lib-modules
          hostPath:
            path: /lib/modules
